name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-central2-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t ${{ GCP_REGION }}-docker.pkg.dev/${{ GCP_PROJECT_ID }}/${{ GCP_REPO_NAME }}/flask-web-app .
        docker push ${{ GCP_REGION }}-docker.pkg.dev/${{ GCP_PROJECT_ID }}/${{ GCP_REPO_NAME }}/flask-web-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_APP_NAME }} \
          --image ${{ GCP_REGION }}-docker.pkg.dev/${{ GCP_PROJECT_ID }}/${{ GCP_REPO_NAME }}/flask-web-app:latest \
          --region ${{ GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
